spring:
  datasource:
    url: jdbc:mysql://localhost:3306/counter?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: member
    password: member1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
<<<<<<< HEAD
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
=======
        format_sql: true 
        show_sql: true
>>>>>>> origin/main

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.

    groups-order: DESC # path, query, body, response 순으로 출력

    tags-sorter: alpha # 태그를 알파벳 순으로 정렬

    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능